# Generated by Django 5.0.6 on 2024-06-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoicemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Invoice_id', models.CharField(blank=True, max_length=255)),
                ('invoice_number', models.CharField(blank=True, max_length=255)),
                ('Customer_id', models.CharField(blank=True, max_length=255)),
                ('Order_id', models.CharField(blank=True, max_length=255)),
                ('Payment_id', models.CharField(blank=True, max_length=255)),
                ('Payment_method', models.CharField(blank=True, max_length=255)),
                ('Gross_amount', models.IntegerField(blank=True)),
                ('Tax_amount', models.IntegerField(blank=True)),
                ('Amount', models.IntegerField(blank=True)),
                ('Amount_paid', models.IntegerField(blank=True)),
                ('Amount_due', models.IntegerField(blank=True)),
                ('Currency', models.CharField(blank=True, max_length=255)),
                ('Billing_address', models.TextField(blank=True)),
                ('Shipping_address', models.TextField(blank=True)),
                ('Billingtime', models.DateTimeField(auto_now=True)),
                ('Status', models.CharField(blank=True, max_length=255)),
                ('Invoice_pdf', models.FileField(null=True, upload_to='../invoice_pdf/')),
                ('Email_id', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentdataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Amount', models.IntegerField(null=True)),
                ('Amount_paid', models.IntegerField(null=True)),
                ('Amount_due', models.IntegerField(null=True)),
                ('Currency', models.CharField(max_length=100, null=True)),
                ('Receipt', models.FileField(upload_to='receipts/')),
                ('Status', models.CharField(max_length=30, null=True)),
                ('Attempts', models.IntegerField(null=True)),
                ('Notes', models.TextField(null=True)),
                ('Created_at', models.DateTimeField(auto_now=True, null=True)),
                ('Payment_Id', models.CharField(blank=True, max_length=255, null=True)),
                ('Order_id', models.CharField(max_length=255, null=True)),
                ('Signature', models.CharField(blank=True, max_length=255, null=True)),
                ('Datetime', models.DateTimeField(auto_now=True)),
                ('Prod_Quantity', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchaseproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Type', models.CharField(max_length=254, null=True)),
                ('Prod_Image1', models.ImageField(null=True, upload_to='')),
                ('Prod_Image2', models.ImageField(null=True, upload_to='')),
                ('Prod_Image3', models.ImageField(null=True, upload_to='')),
                ('Prod_Image4', models.ImageField(null=True, upload_to='')),
                ('Prod_Price', models.IntegerField(null=True)),
                ('Prod_MRP', models.IntegerField(null=True)),
                ('Prod_Offer', models.CharField(max_length=254, null=True)),
                ('Prod_Detail', models.TextField(null=True)),
                ('prod_color', models.CharField(max_length=254, null=True)),
                ('Serial_no', models.IntegerField(null=True)),
                ('Purchase_date', models.DateTimeField(auto_now=True)),
                ('Order_id', models.CharField(max_length=255, null=True)),
                ('Email_id', models.EmailField(max_length=254, null=True)),
                ('Prod_Quantity', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
